Repository Human-Connection/Nitro-Web, pull requests merged in 2018-11, with the labels that each got.

#19 adjust user relation after changing the author relation in the backend
  components/Author.vue
  graphql/UserProfileQuery.js
  nuxt.config.js
  pages/index.vue
  pages/post/_slug/index.vue
  pages/post/_slug/more-info.vue
Labels: blocked

#21 Proxy API Requests
  nuxt.config.js
  package.json
  pages/login.vue
  plugins/apollo-config.js
  yarn.lock
Labels: blocked, important

#22 Fix proxy reload issue
  plugins/apollo-config.js
Labels: blocked, bug, important, staging

#64 adapt docs to styleguide integration
  README.md
Labels: documentation
