Repository Human-Connection/Nitro-Web, pull requests merged in 2019-02, with the labels that each got.

#173 Upgrade dependencies
  .babelrc
  package.json
  styleguide/package.json
  styleguide/src/styleguide/components/SectionPage.vue
  styleguide/src/system/components/layout/Modal/Modal.vue
  styleguide/yarn.lock
  yarn.lock
Labels: PR: reviewed-approved

#175 Upgrade to Nuxt 2.4
  nuxt.config.js
  package.json
  styleguide/package.json
  styleguide/yarn.lock
  yarn.lock
Labels: PR: unreviewed

#183 Update .travis.yml
  .travis.yml
Labels: PR: unreviewed

#192 Added IntersectionObserver polyfill and fixed linting on login
  nuxt.config.js
  pages/login.vue
Labels: PR: unreviewed

#153 Editor
  .gitignore
  .travis.yml
  README.md
  assets/styles/main.scss
  components/ContentMenu.vue
  components/ContributionForm.vue
  components/Editor/Editor.vue
  components/Editor/plugins/eventHandler.js
  components/PostCard.vue
  cypress.env.template.json
  cypress/integration/01.Login.feature
  cypress/integration/03.TagsAndCategories.feature
  cypress/integration/04.AboutMeAndLocation.feature
  cypress/integration/05.ReportContent.feature
  cypress/integration/06.WritePost.feature
  cypress/integration/common/admin.js
  cypress/integration/common/report.js
  cypress/integration/common/settings.js
  cypress/integration/common/steps.js
  cypress/support/commands.js
  cypress/support/factories.js
  cypress/support/index.js
  docker-compose.override.yml
  docker-compose.travis.yml
  graphql/PostMutations.js
  locales/de.json
  locales/en.json
  package.json
  pages/index.vue
  pages/post/_slug/index.vue
  pages/post/_slug/more-info.vue
  pages/post/create.vue
  pages/post/edit/_id.vue
  pages/profile/_slug.vue
  styleguide/src/system/components/data-input/shared/input.js
  styleguide/src/system/icons/svg/bold.svg
  styleguide/src/system/icons/svg/italic.svg
  styleguide/src/system/icons/svg/list-ol.svg
  styleguide/src/system/icons/svg/list-ul.svg
  styleguide/src/system/icons/svg/paragraph.svg
  styleguide/src/system/icons/svg/quote-right.svg
  yarn.lock
Labels: PR: reviewed-approved, feature

#199 194 stop decoding jwt on frontend
  .env.template
  cypress/integration/common/admin.js
  cypress/integration/common/report.js
  cypress/support/factories.js
  docker-compose.yml
  package.json
  pages/settings/index.vue
  store/auth.js
  store/auth.test.js
Labels: PR: unreviewed
