Repository Human-Connection/Nitro-Web, pull requests merged in 2019-01, with the labels that each got.

#123 Lokalise: Translations update
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/it.json
  locales/nl.json
  locales/pl.json
  locales/pt.json
Labels: PR: unreviewed

#111 i18n pluralization
  components/Author.vue
  locales/de.json
  locales/en.json
  pages/post/_slug.vue
  pages/profile/_slug.vue
Labels: PR: reviewed-approved

#129 Improve dropdown
  assets/styles/main.scss
  components/Author.vue
  components/Dropdown.vue
  layouts/blank.vue
  layouts/default.vue
  styleguide/src/system/components/navigation/Menu/MenuItem.vue
Labels: PR: unreviewed

#115 Multistage build docker
  .dockerignore
  .travis.yml
  Dockerfile
  cypress/integration/common/steps.js
  docker-compose.override.yml
  docker-compose.travis.yml
  docker-compose.yml
  package.json
  yarn.lock
Labels: PR: unreviewed

#9 Locations & About Me
  .dockerignore
  .env.template
  .travis.yml
  Dockerfile
  README.md
  components/Author.vue
  components/LoadMore.vue
  components/PostCard.vue
  cypress.json
  cypress/integration/01.Login.feature
  cypress/integration/02.Internationalization.feature
  cypress/integration/03.TagsAndCategories.feature
  cypress/integration/04.AboutMeAndLocation.feature
  cypress/integration/common/admin.js
  cypress/integration/common/settings.js
  cypress/integration/common/steps.js
  cypress/support/commands.js
  cypress/support/config.js
  cypress/support/helpers.js
  docker-compose.yml
  graphql/UserProfileQuery.js
  layouts/default.vue
  locales/de.json
  locales/en.json
  nuxt.config.js
  pages/index.vue
  pages/post/_slug/index.vue
  pages/post/_slug/more-info.vue
  pages/profile/_slug.vue
  pages/settings/index.vue
  plugins/apollo-config.js
  plugins/axios.js
  plugins/i18n.js
  plugins/keep-alive.js
  server/index.js
  store/auth.js
  styleguide/package.json
  styleguide/src/system/components/data-input/Select/Select.vue
  styleguide/yarn.lock
Labels: PR: reviewed-approved, feature

#107 Report Content
  assets/styles/imports/_tooltip.scss
  assets/styles/main.scss
  components/ContentMenu.vue
  components/PostCard.vue
  components/ReportModal.vue
  cypress/fixtures/users.json
  cypress/integration/04.AboutMeAndLocation.feature
  cypress/integration/05.ReportContent.feature
  cypress/integration/common/report.js
  cypress/integration/common/steps.js
  cypress/support/commands.js
  cypress/support/config.js
  cypress/support/helpers.js
  graphql/ModerationListQuery.js
  layouts/default.vue
  locales/de.json
  locales/en.json
  middleware/isAdmin.js
  middleware/isModerator.js
  nuxt.config.js
  package.json
  pages/admin.vue
  pages/moderation.vue
  pages/moderation/index.vue
  pages/post/_slug/index.vue
  pages/profile/_slug.vue
  pages/settings.vue
  store/modal.js
  styleguide/package.json
  styleguide/src/system/components/layout/Card/style.scss
  styleguide/src/system/components/layout/Modal/Modal.vue
  styleguide/src/system/components/layout/Modal/demo.md
  styleguide/src/system/components/layout/Modal/style.scss
  styleguide/src/system/icons/svg/flag.svg
  styleguide/src/system/styles/shared.scss
  styleguide/src/system/styles/shared/_animations.scss
  styleguide/src/system/styles/shared/_transitions.scss
  styleguide/src/system/tokens/_examples/dark-purple/box-shadow.yml
  styleguide/src/system/tokens/border-radius.yml
  styleguide/yarn.lock
  yarn.lock
Labels: PR: reviewed-approved, feature

#149 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: PR: reviewed-approved

#145 fix mobile friendliness for post
  pages/post/_slug.vue
Labels: PR: unreviewed
